title: どんぐりの森と秘密の扉
language: ja
author: Jianqiang Sun
copyright: '2025'


only_build_toc_files: true

execute:
  execute_notebooks: force
  allow_errors: true
  timeout: 600


latex:
  latex_documents:
    targetname: book.tex  

repository:
  url: https://github.com/biopapyrus/py
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
      <p>CC BY-NC 4.0</p>

launch_buttons:
  notebook_interface: 'jupyterlab'
  colab_url: 'https://colab.research.google.com'
  binderhub_url: 'https://mybinder.org'
  thebe: true

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinxcontrib.bibtex
  config:
    html_show_copyright: false
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings:
      - mystnb.unknown_mime_type
    mathjax_path: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
    bibtex_bibfiles:
      - references.bib
    bibtex_reference_style: super

parse:
  myst_enable_extensions:
    - deflist
    - amsmath
    - dollarmath
    - html_image
